server:
  port: 8088

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: api-driver
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0

feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 1000
ribbon:
  ConnectTimeout: 10000 # 连接超时时间(ms)
  ReadTimeout: 10000 # 通信超时时间(ms)