server:
  port: 8081
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: api-passenger
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0

feign:
  client:
    config:
      default:
        connectTimeout: 4000
        readTimeout: 4000
ribbon:
  ConnectTimeout: 20000 # 连接超时时间(ms)
  ReadTimeout: 20000 # 通信超时时间(ms)
