server:
  port: 8081
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: api-passenger
  redis:
    host: 192.168.132.128
    port: 6379
    database: 0
    password: 123456

feign:
  client:
    config:
      default:
        connectTimeout: 1000
        readTimeout: 500
ribbon:
  ConnectTimeout: 5000 # 连接超时时间(ms)
  ReadTimeout: 5000 # 通信超时时间(ms)
